name: Docker release reusable workflow

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      BUILD_ARGS:
        required: true
      DOCKER_FILE:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  release-base-image:
    if: ${{ startsWith(github.ref_name, '${{env.SERVICE_NAME}}') }}
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Get the Image tag
        env:
          TAG: ${{ github.ref_name }}
        run: echo "FULL_IMAGE_TAG=concordium/${{ env.SERVICE_NAME }}:${TAG##${{ env.SERVICE_NAME}}-}" >> $GITHUB_ENV

      - name: Check if image exist
        run: |
          set +e
          docker manifest inspect ${{ env.FULL_IMAGE_TAG }}
          exitcode=$?
          if [ $exitcode -eq "0" ]; then
            echo "Error: ${{ env.FULL_IMAGE_TAG }} already exist"
            exit 1
          fi

      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          tags: ${{ env.FULL_IMAGE_TAG }}
          no-cache: true
          push: false
          build-args: |
            ${{BUILD_ARGS}}
